http_port : 8081 #对外api接口端口号
http_timeout : 60 #http请求超时时间（秒）

#服务注册中心
etcd :
  address: 127.0.0.1:2379 #集群etcd多地址用，号分割 例如 127.0.0.1:2379,192.168.0.14:2379

# mysql数据库
database:
  user_name: root #数据库用户名
  user_passwd: root #数据库用户密码
  address: 172.17.29.132:3306 #数据库地址
  db_name: seal_reviews #数据库名
  debug: false #debug模式
  table_prefix: seal_ #数据表前缀
#redis数据库
redis:
  address: 172.17.29.132:6379 #地址
  db: 0 #默认使用第一个数据库
#mns队列
mns:
  url: xxxxx
  access_key_id: xxxx
  access_key_secret: xxxxx
  env: develop

#jaeger链路追踪
jaeger:
  jaeger_tracer_addr: 127.0.0.1:6831
