version: '3'
services:

    redis:
        image: redis:6.0.10
        restart: always
        container_name: ldm-redis
        privileged: true
        command: redis-server /etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data

