version: '3'
services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        restart: always
        container_name: jaeger
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        ports:
        - 5775:5775/udp
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 14268:14268
        - 9411:9411
    swagger:
        image: swaggerapi/swagger-ui:latest
        restart: always
        container_name: swagger
        volumes:
            - ./common/swagger:/usr/share/nginx/html/swagger
        ports:
            - 9095:8080
    #redis:
        #image: redis:6.0.10
        #restart: always
        #container_name: redis
        #privileged: true
        #command: redis-server /etc/redis/redis.conf
            #ports:
            #- "6379:6379"
            #volumes:
            #- ./redis/redis.conf:/etc/redis/redis.conf
            #- ./redis/data:/data
    #etcd:
        #image: quay.io/coreos/etcd:v3.3.9
        #restart: always
        #container_name: etcd
        #privileged: true
        #command: ""
            #ports:
            #- 2379-2380->2379-2380
    api-gateway-srv:
        restart: always
        container_name: api-gateway-srv
        build:
            context: ./srvs/gateway
            dockerfile: Dockerfile
        command: ""
        volumes:
            - ./config/:/opt/config/
        ports:
            - 8081:8081
    api-hello-srv:
        restart: always
        container_name: api-hello-srv
        build:
            context: ./srvs/hello
            dockerfile: Dockerfile
        command: ""
        volumes:
            - ./config/:/opt/config/
        ports:
            - 9507:9507
    api-project-srv:
        restart: always
        container_name: api-project-srv
        build:
            context: ./srvs/project
            dockerfile: Dockerfile
        command: ""
        volumes:
            - ./config/:/opt/config/
        ports:
            - 9508:9508
    api-liveroom-srv:
        restart: always
        container_name: api-liveroom-srv
        build:
            context: ./srvs/liveroom
            dockerfile: Dockerfile
        command: ""
        volumes:
            - ./config/:/opt/config/
        ports:
            - 9509:9509
