version: '3'
services:
    api-hello-srv:
        restart: always
        container_name: api-hello-srv
        build:
            dockerfile: ./srvs/hello/Dockerfile
        command: ""
        volumes:
            - ./config/:/opt/config/
        ports:
            - "9507:9507"
    api-project-srv:
        restart: always
        container_name: api-project-srv
        build:
            dockerfile: ./srvs/project/Dockerfile
        command: ""
        volumes:
            - ./config/:/opt/config/
        ports:
            - "9508:9508"
    api-liveroom-srv:
        restart: always
        container_name: api-liveroom-srv
        build:
            dockerfile: ./srvs/liveroom/Dockerfile
        command: ""
        volumes:
            - ./config/:/opt/config/
        ports:
            - "9509:9509"
